#!/bin/sh

echo "Unloading daemon"

if [[ $1 == remove || $1 == purge ]]; then
    /bin/launchctl unload /Library/LaunchDaemons/com.matchstic.reprovisiond.plist 2> /dev/null || /sbin/launchctl unload /Library/LaunchDaemons/com.matchstic.reprovisiond.plist
fi

exit 0
