//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Preferences/PSTableCell.h>

@class UIControl;

@interface PSControlTableCell : PSTableCell
{
    UIControl *_control;
}

- (void)controlChanged:(id)arg1;
- (id)controlValue;
@property(retain, nonatomic) UIControl *control;
- (void)dealloc;
- (id)valueLabel;
- (_Bool)canReload;
- (id)newControl;
- (void)refreshCellContentsWithSpecifier:(id)arg1;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2 specifier:(id)arg3;

@end

